name: CI + Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test

  release:
    name: Bump & Publish
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false 

      - name: Set git identity (as user)
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Set remote URL with token
        run: |
          git remote set-url origin https://albertolinde:${{ secrets.PERSONAL_GH_TOKEN }}@github.com/AlbertoLinde/universal-contact-notifier.git

      - name: Debug remote URL
        run: git remote -v

      - name: Bump patch version
        run: |
          npm version patch -m "chore(release): v%s [skip ci]"

      - name: Push version bump
        run: git push origin main --follow-tags

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
